export const fontFamily = {
  bebasNeue: ["Bebas Neue", "sans-serif"],
  poppins: ["Poppins", "sans-serif"],
  merriweather: ["Merriweather", "serif"],
  openSans: ["Open Sans", "sans-serif"],
  nunitoSans: ["Nunito Sans", "sans-serif"],
  nunito: ["Nunito", "sans-serif"],
  sourceSans3: ["Source Sans 3", "sans-serif"],
  bitter: ["Bitter", "serif"],
  raleway: ["Raleway", "sans-serif"],
  oswald: ["Oswald", "sans-serif"],
  PTSans: ["PT Sans", "sans-serif"],
  PTSerif: ["PT Serif", "serif"],
  robotoSlab: ["Roboto Slab", "serif"],
  roboto: ["Roboto", "sans-serif"],
  loto: ["Loto", "sans-serif"],
  lora: ["Lora", "serif"],
  montserrat: ["Montserrat", "sans-serif"],
  playfairDisplay: ["Playfair Display", "serif"],
  ubuntu: ["Ubuntu", "sans-serif"],
  abrilFatface: ["Abril Fatface", "serif"],
  faunaOne: ["Fauna One", "serif"],
  cinzel: ["Cinzel", "serif"],
  libreBaskerville: ["Libre Baskerville", "serif"],
  fjallaOne: ["Fjalla One", "sans-serif"],
  mulish: ["Mulish", "sans-serif"],
  spaceMono: ["Space Mono", "monospace"],
  notoSans: ["Noto Sans", "sans-serif"],
  rubik: ["Rubik", "sans-serif"],
  spectral: ["Spectral", "serif"],
  alkatra: ["Alkatra", "system-ui"],
  sedgwickAve: ["Sedgwick Ave", "cursive"],
};
